#!/bin/bash

notify-send --icon=/usr/share/unity/icons/information_icon.svg "Adding PPAs..."

add-apt-repository --yes ppa:nilarimogard/webupd8
add-apt-repository --yes ppa:webupd8team/java

add-apt-repository --yes ppa:tsbarnes/indicator-keylock
add-apt-repository --yes ppa:webupd8team/nemo
add-apt-repository --yes ppa:jconti/recent-notifications
add-apt-repository --yes ppa:linrunner/tlp
add-apt-repository --yes ppa:libreoffice/libreoffice-5-1
add-apt-repository --yes ppa:mc3man/trusty-media
add-apt-repository --yes ppa:costales/unity-webapps-telegram
add-apt-repository --yes ppa:webupd8team/unstable
add-apt-repository --yes ppa:noobslab/apps
add-apt-repository --yes ppa:otto-kesselgulasch/gimp
add-apt-repository --yes ppa:atareao/atareao
add-apt-repository --yes ppa:yannubuntu/boot-repair


notify-send --icon=/usr/share/unity/icons/information_icon.svg "Updating Repositories Cache."
apt-get -y update
notify-send --icon=/usr/share/unity/icons/information_icon.svg "Upgrading System."
apt-get -y upgrade
apt-get -y dist-upgrade
notify-send --icon=/usr/share/unity/icons/information_icon.svg "Removing Absolete Programs and Cleaning Up..."
apt-get -y autoremove
apt-get -y autoclean

notify-send --icon=/usr/share/unity/icons/information_icon.svg "Installing Programs."

apt-get install -y preload ubuntu-tweak aptitude acpi gdebi mc tlp unity-tweak-tool tlp-rdw ppa-purge oracle-java9-installer ubuntu-wallpapers-karmic ubuntu-wallpapers-lucid ubuntu-wallpapers-maverick ubuntu-wallpapers-natty ubuntu-wallpapers-oneiric ubuntu-wallpapers-precise ubuntu-wallpapers-quantal ubuntu-wallpapers-raring ubuntu-wallpapers-saucy nemo nemo-fileroller nemo-compare nemo-media-columns nemo-pastebin nemo-seahorse nemo-share nemo-emblems nemo-image-converter dconf-tools plymouth-theme-solar whois ncdu nmap guake gstreamer0.10-ffmpeg pepperflashplugin-nonfree unity-webapps-telegram libreoffice-style-sifr telegram-desktop my-weather-indicator boot-repair

notify-send --icon=/usr/share/unity/icons/information_icon.svg "Unhiding Startup Applications."
sed -i 's/NoDisplay=true/NoDisplay=false/g' /etc/xdg/autostart/*.desktop
notify-send --icon=/usr/share/unity/icons/information_icon.svg "Starting TLP."
tlp start

notify-send --icon=/usr/share/unity/icons/information_icon.svg "Setting Up Nemo."

gsettings set org.gnome.desktop.background show-desktop-icons false
xdg-mime default nemo.desktop inode/directory application/x-gnome-saved-search
nautilus -q

notify-send --icon=/usr/share/unity/icons/information_icon.svg "Setting Up Plymouth Theme."
update-alternatives --config default.plymouth

notify-send --icon=/usr/share/unity/icons/information_icon.svg "Setting up Pepperflash Plugin."
update-pepperflashplugin-nonfree --install

notify-send --icon=/usr/share/unity/icons/information_icon.svg "Clearing History."
cat /dev/null > ~/.bash_history && history -c && exit
exit 0﻿
